# Generated by Django 3.1.5 on 2021-01-27 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Pacotes')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100, verbose_name='Nome do Hotel')),
                ('slug', models.CharField(max_length=100, verbose_name='Apelido do Hotel')),
                ('image', models.URLField(verbose_name='Imagem')),
                ('price', models.IntegerField(verbose_name='Valor R$')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrines.title')),
            ],
        ),
    ]
