# Generated by Django 3.1.5 on 2021-01-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='pacote',
        ),
    ]
