# Generated by Django 3.1.5 on 2021-01-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrines', '0002_remove_hotel_pacote'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome da cidade')),
                ('slug', models.CharField(max_length=50, verbose_name='Apelido da cidade')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
            ],
        ),
    ]
