# Generated by Django 3.1.5 on 2021-01-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrines', '0003_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do País')),
                ('slug', models.SlugField(verbose_name='Apelido do país')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do País')),
                ('slug', models.SlugField(verbose_name='Apelido do país')),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(verbose_name='Apelido da cidade'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(max_length=50, verbose_name='Abreviação do estado'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(verbose_name='Apelido do Hotel'),
        ),
    ]
