# Generated by Django 3.1.5 on 2021-01-27 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrines', '0004_auto_20210127_1525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='Vitrine',
        ),
    ]
