# Generated by Django 3.1.5 on 2021-01-27 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrines', '0005_auto_20210127_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vitrines.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='vitrine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vitrines.vitrine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome da categoria'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(verbose_name='Apelido da categoria'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome do país'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(verbose_name='Apelido do hotel'),
        ),
        migrations.AlterField(
            model_name='vitrine',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tipo de pacote'),
        ),
    ]
