# Generated by Django 3.1.5 on 2021-01-27 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrines', '0006_auto_20210127_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='vitrine',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vitrines.vitrine'),
        ),
    ]
