# Generated by Django 3.1.5 on 2021-01-28 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrines', '0007_auto_20210127_1928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vitrine',
            new_name='Evento',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='vitrine',
            new_name='evento',
        ),
    ]
