# Generated by Django 3.1.5 on 2021-01-28 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrines', '0008_auto_20210127_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100, verbose_name='Nome do Hotel')),
                ('slug', models.SlugField(verbose_name='Apelido do hotel')),
                ('image', models.URLField(verbose_name='Imagem')),
                ('price', models.IntegerField(verbose_name='Valor R$')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrines.evento')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='country',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='evento',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
