# Generated by Django 3.1.5 on 2021-01-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrines', '0009_auto_20210127_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Evento'),
        ),
    ]
