# Generated by Django 3.1.5 on 2021-01-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrines', '0010_auto_20210128_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome da cidade')),
                ('slug', models.SlugField(verbose_name='Apelido da cidade')),
                ('state', models.CharField(max_length=50, verbose_name='Abreviação do estado')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.ManyToManyField(to='vitrines.City'),
        ),
    ]
