# Generated by Django 3.1.5 on 2021-01-29 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrines', '0011_auto_20210128_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome da categoria')),
                ('slug', models.SlugField(verbose_name='Apelido da categoria')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='city',
        ),
        migrations.AlterField(
            model_name='item',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrines.evento'),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do país')),
                ('slug', models.SlugField(verbose_name='Apelido do país')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrines.city')),
            ],
        ),
    ]
