# Generated by Django 3.1.5 on 2021-01-29 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrines', '0012_auto_20210128_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Cidade'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Região'},
        ),
        migrations.RemoveField(
            model_name='country',
            name='city',
        ),
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vitrines.city'),
        ),
    ]
