# Generated by Django 3.1.5 on 2021-01-29 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrines', '0015_auto_20210129_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='TESTE CLASS CATEGORY', max_length=50, verbose_name='Nome da categoria'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, help_text='TESTE AQUI CLASSE ITEM', null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrines.category'),
        ),
    ]
