# Generated by Django 3.1.5 on 2021-01-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrines', '0017_auto_20210129_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome da categoria'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(verbose_name='Slug da categoria'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(verbose_name='Slug da cidade'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(help_text='Ex.: RN', max_length=50, verbose_name='Abreviação do estado'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(verbose_name='Slug do país'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(verbose_name='Slug do hotel'),
        ),
    ]
